apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: posa-web
      spec:
        template:
          spec:
            containers:
            - name: posa-web
              image: "posa-new:release"
              env:
                - name: PHX_ORGANIZATIONS
                  value: "puzzle"
                - name: PHX_INITIAL_SYNC
                  value: "false"
                - name: PHX_START_STORAGE
                  value: "true"
                - name: PHX_START_SYNC
                  value: "true"
                - name: PHX_SYNC_DELAY_MS
                  value: "7200000" # 7200000ms = 2 hours
  - patch: |-
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: posa
      spec:
        host: pitc-posa-prod.ocp.cloudscale.puzzle.ch
  - patch: |-
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: posa-external
      spec:
        host: opensource.puzzle.ch

