apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: posa
      spec:
        host: pitc-posa-prod.ocp.cloudscale.puzzle.ch
  - patch: |-
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: posa-external
      spec:
        host: opensource.puzzle.ch

