---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: elixir-upstream
  annotations:
    puzzle.ch/purpose: Upstream image change trigger
spec:
  dockerImageRepository: docker.io/hexpm/elixir
  tags:
    - from:
        kind: DockerImage
        name: docker.io/hexpm/elixir:1.14.1-erlang-25.1.1-alpine-3.16.2
      importPolicy:
        scheduled: true
      name: latest
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: posa
  name: posa
spec:
  successfulBuildsHistoryLimit: 3
  output:
    to:
      kind: ImageStreamTag
      name: posa:latest
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 128Mi
  source:
    git:
      ref: master
      uri: https://github.com/Kagemaru/posa.git
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      from:
        kind: ImageStreamTag
        name: elixir-upstream:1.14.1-erlang-25.1.1-alpine-3.16.2
      env:
        - name: TZ
          value: Europe/Berlin
        - name: PHX_GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: phx-github-token
              key: token
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: posa-secret-key-base
              key: key
  triggers:
    - imageChange:
        from:
          kind: ImageStreamTag
          name: elixir-upstream:1.14.1-erlang-25.1.1-alpine-3.16.2
      type: ImageChange
...
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: posa
spec:
  lookupPolicy:
    local: true
...
