---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: posa
  name: posa
spec:
  successfulBuildsHistoryLimit: 3
  output:
    to:
      kind: ImageStreamTag
      name: posa:latest
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 128Mi
  source:
    git:
      ref: master
      uri: https://github.com/Kagemaru/posa.git
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      env:
        - name: TZ
          value: Europe/Berlin
        - name: PHX_SYNC_DELAY_MS
          value: 900000 # 900000 ms = 15min
        - name: PHX_GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: phx-github-token
              key: token
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: posa-secret-key-base
              key: key
      buildArgs:
      - name: secret_key_base
        valueFrom:
          secretKeyRef:
            key: key_base
            name: secret_key_base
...
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: posa
spec:
  lookupPolicy:
    local: true
...
