apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: posa-web
  name: posa-web
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from": { "kind":"ImageStreamTag", "name": "posa-new:release" },
          "fieldPath": "spec.template.spec.containers[?(@.name==\"posa-web\")].image"
        }
      ]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posa-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: posa-web
    spec:
      containers:
      - name: posa-web
        image: posa:release
        command:
          - bash
          - -c
          - bin/posa start
        env:
          - name: PHX_SYNC_DELAY_MS
            value: 900000 # 900000 ms = 15min
          - name: TZ
            value: Europe/Berlin
          - name: PHX_GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: phx-github-token
                key: token
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: posa-secret-key-base
                key: key
          # - name: PHOENIX_ENV
          #   value: production
          # - name: SENTRY_DSN
          #   valueFrom:
          #     secretKeyRef:
          #       key: dsn
          #       name: sentry-dsn
          # - name: LIVENESS_IP_ADDRESS
          #   valueFrom:
          #     fieldRef:
          #       fieldPath: status.podIP
          # livenessProbe:
          #   failureThreshold: 10
          #   httpGet:
          #     path: /healthz
          #     port: 3000
          #   initialDelaySeconds: 20
          #   periodSeconds: 30
          #   timeoutSeconds: 30
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
          limits:
            cpu: 1
            memory: 2Gi
      restartPolicy: Always
      # volumes: []
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: posa-web
  name: posa-web
spec:
  ports:
  - name: 4000-tcp
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: posa-web
  type: ClusterIP

