---
apiVersion: v1
kind: BuildConfig
metadata:
  name: posa
spec:
  strategy:
    dockerStrategy:
      buildArgs:
      - name: secret_key_base
        valueFrom:
          secretKeyRef:
            key: key_base
            name: secret_key_base
