---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posa-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posa-web
    name: posa-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: posa-web
    spec:
      containers:
      - name: posa-web
        image: posa:release
        command:
          - bash
          - -c
          - bin/posa start
        env:
          - name: TZ
            value: Europe/Berlin
          - name: PHX_SYNC_DELAY_MS
            value: 7200000 # 7200000ms = 2 hours
