---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: posa
spec:
  host: pitc-posa-int.ocp.cloudscale.puzzle.ch
...
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: posa-external
$patch: delete
...
