apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: posa-web
      spec:
        template:
          spec:
            containers:
            - name: posa-web
              env:
                - name: PHX_SYNC_DELAY_MS
                  value: "7200000" # 7200000ms = 2 hours
  - patch: |-
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: posa
      spec:
        host: pitc-posa-int.ocp.cloudscale.puzzle.ch
  - patch: |-
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: posa-external
      $patch: delete
