---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: posa-web
      spec:
        template:
          spec:
            containers:
            - name: posa-web
              image: "posa-new:release"
              env:
                - name: PHX_ORGANIZATIONS
                  value: "puzzle"
                - name: PHX_INITIAL_SYNC
                  value: "false"
                - name: PHX_START_STORAGE
                  value: "true"
                - name: PHX_START_SYNC
                  value: "true"
                - name: PHX_SYNC_DELAY_MS
                  value: "3600000" # 3600000ms = 1 hour
  - patch: |-
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: posa
      spec:
        host: pitc-posa-int.ocp.cloudscale.puzzle.ch
  - patch: |-
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: posa-external
      $patch: delete
  - patch: |-
      apiVersion: image.openshift.io/v1
      kind: ImageStream
      metadata:
        name: posa-new
      spec:
        dockerImageRepository: registry.puzzle.ch/posa/elixir-int
        tags:
          - name: latest
            annotations:
              openshift.io/imported-from: registry.puzzle.ch/posa/elixir-int
            from:
              name: registry.puzzle.ch/posa/elixir-int:latest
              kind: DockerImage
          - name: release
            annotations:
              openshift.io/imported-from: registry.puzzle.ch/posa/elixir-int
            from:
              name: registry.puzzle.ch/posa/elixir-int:release
              kind: DockerImage
...      
