---
name: Build and push Docker image for production

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.PUZZLE_REGISTRY }}
          username: ${{ secrets.PUZZLE_REGISTRY_USERNAME }}
          password: ${{ secrets.PUZZLE_REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.PUZZLE_REGISTRY }}/pitc-ruby-public/posa/web:latest
            ${{ secrets.PUZZLE_REGISTRY }}/pitc-ruby-public/posa/web:production
            ${{ secrets.PUZZLE_REGISTRY }}/pitc-ruby-public/posa/web:${{ github.sha }}
