---
name: Build and push Docker image for integration

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.PUZZLE_REGISTRY }}
          username: ${{ secrets.PUZZLE_REGISTRY_USERNAME }}
          password: ${{ secrets.PUZZLE_REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            posa/elixir-int:latest
            posa/elixir-int:${{ github.sha }}
