---
name: Elixir Tests

"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  MIX_ENV: test
  SECRET_KEY_BASE: "kNdLk1/ffDLY4T1sKLmBffS0SpG7hzpq6/rRD7yM6W25l2Q9BwXlOGumdJWvZygA"
  PHX_GITHUB_TOKEN: fake

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - id: setup-elixir
        uses: erlef/setup-beam@v1
        with:
          version-type: strict
          version-file: ".tool-versions"
      - id: mix-cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-${{ steps.setup-elixir.outputs.otp-version }}-${{ steps.setup-elixir.outputs.elixir-version }}-test-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-${{ steps.setup-elixir.outputs.otp-version }}-${{ steps.setup-elixir.outputs.elixir-version }}-test-mix-
      - name: Install dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile
      - name: Run tests
        run: mix test
